routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Server;
use Illuminate\Support\Facades\Request;

Route::get('/', 'HomeController@index');

Route::resource('servers', 'ServersController');

Route::resource('products', 'ProductsController');
Route::resource('purposes', 'PurposesController');
Route::resource('environments', 'EnvironmentsController');
Route::resource('hardware', 'HardwareController');
Route::resource('location', 'LocationController');
Route::get('details/{id}', 'ServersController@showdetails')->name('details');;

Route::any('/search',function(){
    $q = Request::get ( 'q' );
    $server = Server::where('hostname','LIKE','%'.$q.'%')->orWhere('serial','LIKE','%'.$q.'%')->get();
    if(count($server) > 0)
        return view('servers.search')->withDetails($server)->withQuery ( $q );
    else return view ('servers.search')->withMessage('No Servers found. Try to search again !');
});

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable = [
        'name',
        'region',
    ];

    public function server()
    {
        return $this->hasMany(App\Models\Server::class);
    }
}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Location;

class LocationController extends Controller
{
    public function index() {
        $locations = Location::paginate(10);
        return view('location.index', compact('locations'));
    }

    public function create() {
        return view('location.create');
    }

    public function store(Request $request) {

        $validatedData = $request->validate([
            'name' => 'required|max:60|unique:locations,name',
            'region' => 'required|max:20',
        ]);
        $location = Location::create($validatedData);
   
        return redirect('/location')->with('success', 'Location has been successfully saved');
    }

    public function edit($id)
    {
        $location = Location::findOrFail($id);

        return view('location.edit', compact('location'));
    }

    public function update(Request $request, $id)
{
        $validatedData = $request->validate([
            'name' => 'required|max:60|unique:locations,name,'.$id,
            'region' => 'required|max:20',
        ]);
        Location::whereId($id)->update($validatedData);

        return redirect('/location')->with('success', 'Location has been successfully updated');
}

    public function destroy($id) {
        $location = Location::findOrFail($id);
        $location->delete();

        return redirect('/location')->with('success', 'Location has been deleted');
    }
}

resources/views/location/create.blade.php
@extends('layouts.master')
@section('content')

@section('pagename')
    Create a new location enrty
@endsection
@section('breadcrumb', 'Location')
<div class="card uper">
    <div class="card-header">
        Add new location
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('location.store') }}">
            <div class="form-group">
                @csrf
                <label for="name">Location Name:</label>
                <input type="text" class="form-control" name="name" value="{{ old('name') }}"/>
            </div>
            <div class="form-group">
                <label for="region">Region Description:</label>
                <input type="text" class="form-control" name="region" value="{{ old('region') }}"/>
            </div>

            <button type="submit" class="btn btn-primary">Create new location</button>
        </form>
    </div>
</div>
@endsection

resources/views/location/edit.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    Edit Location: {{ $location->name }}
@endsection
@section('breadcrumb', 'Location')
<div class="card uper">
    <div class="card-header">
        Edit Location: <strong>{{ $location->name }}</strong>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('location.update', $location->id) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="name">Location Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $location->name }}"/>
            </div>
            <div class="form-group">
                <label for="price">Region:</label>
                <input type="text" class="form-control" name="region" value="{{ $location->region }}"/>
            </div>

            <button type="submit" class="btn btn-primary">Update Location</button>
        </form>
    </div>
</div>
@endsection

resources/views/location/index.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    List all locations/regions
@endsection
@section('breadcrumb', 'Location')
<div class="uper">
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br/>
    @endif

    <a href="{{ route('location.create') }}" class="btn btn-primary" style="margin-bottom:10px">Create new location</a>

    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List all locations/regions</h3>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <td>ID</td>
                                <td>Location Name</td>
                                <td>Region</td>
                                <td colspan="2">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($locations as $location)
                                <tr>
                                    <td>{{$location->id}}</td>
                                    <td><a href="{{ route('location.edit', $location->id)}}">{{$location->name}}</a>
                                    </td>
                                    <td>{{$location->region}}</td>
                                    <td><a href="{{ route('location.edit', $location->id)}}" class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                        <form action="{{ route('location.destroy', $location->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {!! $locations->links() !!}

    <div>
@endsection