routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Server;
use Illuminate\Support\Facades\Request;

Route::get('/', 'HomeController@index');

Route::resource('servers', 'ServersController');

Route::resource('products', 'ProductsController');
Route::resource('purposes', 'PurposesController');
Route::resource('environments', 'EnvironmentsController');
Route::resource('hardware', 'HardwareController');
Route::resource('location', 'LocationController');
Route::get('details/{id}', 'ServersController@showdetails')->name('details');;

Route::any('/search',function(){
    $q = Request::get ( 'q' );
    $server = Server::where('hostname','LIKE','%'.$q.'%')->orWhere('serial','LIKE','%'.$q.'%')->get();
    if(count($server) > 0)
        return view('servers.search')->withDetails($server)->withQuery ( $q );
    else return view ('servers.search')->withMessage('No Servers found. Try to search again !');
});

app/Models/Purpose.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Purpose extends Model
{
    protected $fillable = [
        'name',
        'description',
    ];

    public function server()
    {
        return $this->hasMany(App\Models\Server::class);
    }
}

app/Http/Controllers/API/PurposeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PurposeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/purpose/create.blade.php
@extends('layouts.master')

@section('content')
@section('pagename')
    Add Purpose
@endsection
@section('breadcrumb', 'Purpose')
<div class="card uper">
    <div class="card-header">
        Add Purpose
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('purposes.store') }}">
            <div class="form-group">
                @csrf
                <label for="name">Purpose Name:</label>
                <input type="text" class="form-control" name="name" value="{{ old('name') }}"/>
            </div>
            <div class="form-group">
                <label for="description">Purpose Description:</label>
                <input type="text" class="form-control" name="description" value="{{ old('description') }}"/>
            </div>
            <button type="submit" class="btn btn-primary">Create Purpose</button>
        </form>
    </div>
</div>
@endsection

resources/views/purpose/edit.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    Edit Purpose: {{ $purpose->name }}
@endsection
@section('breadcrumb', 'Purpose')
<div class="card uper">
    <div class="card-header">
        Edit Purpose: <strong>{{ $purpose->name }}</strong>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('purposes.update', $purpose->id) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="name">Purpose Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $purpose->name }}"/>
            </div>
            <div class="form-group">
                <label for="price">Product Description:</label>
                <input type="text" class="form-control" name="description" value="{{ $purpose->description }}"/>
            </div>

            <button type="submit" class="btn btn-primary">Update {{ $purpose->name }}</button>
        </form>
    </div>
</div>
@endsection

resources/views/purpose/index.blade.php
@extends('layouts.master')

@section('content')
@section('pagename')
    List all purposes
@endsection
@section('breadcrumb', 'Purpose')
<div class="uper">
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br/>
    @endif

    <a href="{{ route('purposes.create') }}" class="btn btn-primary" style="margin-bottom:10px">Create purpose</a>
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List all purposes</h3>
                    </div>
                    <div class="card-body">

                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <td>ID</td>
                                <td>Name</td>
                                <td>Description</td>
                                <td colspan="2">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($purposes as $purpose)
                                <tr>
                                    <td>{{$purpose->id}}</td>
                                    <td><a href="{{ route('purposes.edit', $purpose->id)}}">{{$purpose->name}}</a></td>
                                    <td>{{$purpose->description}}</td>
                                    <td><a href="{{ route('purposes.edit', $purpose->id)}}"
                                           class="btn btn-primary">Edit</a></td>
                                    <td>
                                        <form action="{{ route('purposes.destroy', $purpose->id)}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {!! $purposes->links() !!}

    <div>
@endsection