routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Server;
use Illuminate\Support\Facades\Request;

Route::get('/', 'HomeController@index');

Route::resource('servers', 'ServersController');

Route::resource('products', 'ProductsController');
Route::resource('purposes', 'PurposesController');
Route::resource('environments', 'EnvironmentsController');
Route::resource('hardware', 'HardwareController');
Route::resource('location', 'LocationController');
Route::get('details/{id}', 'ServersController@showdetails')->name('details');;

Route::any('/search',function(){
    $q = Request::get ( 'q' );
    $server = Server::where('hostname','LIKE','%'.$q.'%')->orWhere('serial','LIKE','%'.$q.'%')->get();
    if(count($server) > 0)
        return view('servers.search')->withDetails($server)->withQuery ( $q );
    else return view ('servers.search')->withMessage('No Servers found. Try to search again !');
});

app/Models/Environment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Environment extends Model
{
    protected $fillable = [
        'name',
        'description',
    ];

    public function server()
    {
        return $this->hasMany(App\Models\Server::class);
    }
}

app/Http/Controllers/EnvironmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Environment;

class EnvironmentsController extends Controller
{
    public function index() {
        $environments = Environment::paginate(10);
        return view('environment.index', compact('environments'));
    }

    public function create() {
        return view('environment.create');
    }

    public function store(Request $request) {

        $validatedData = $request->validate([
            'name' => 'required|max:60|unique:environments,name',
            'description' => 'required|max:255',
        ]);
        $environments = Environment::create($validatedData);
   
        return redirect('/environments')->with('success', 'environment has been successfully saved');
    }

    public function edit($id)
    {
        $environment = Environment::findOrFail($id);

        return view('environment.edit', compact('environment'));
    }

    public function update(Request $request, $id)
{
        $validatedData = $request->validate([
            'name' => 'required|max:60|unique:environments,name,'.$id,
            'description' => 'required|max:255',
        ]);
        Environment::whereId($id)->update($validatedData);

        return redirect('/environments')->with('success', 'environment has been successfully updated');
}

    public function destroy($id) {
        $environment = Environment::findOrFail($id);
        $environment->delete();

        return redirect('/environments')->with('success', 'environment has been successfully deleted');
    }
}

resources/views/environment/create.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    Add Environment
@endsection
@section('breadcrumb', 'environment')
<div class="card uper">
    <div class="card-header">
        Add Environment
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('environments.store') }}">
            <div class="form-group">
                @csrf
                <label for="name">Environment Name:</label>
                <input type="text" class="form-control" name="name" value="{{ old('name') }}"/>
            </div>
            <div class="form-group">
                <label for="description">Environment Description:</label>
                <input type="text" class="form-control" name="description" value="{{ old('description') }}"/>
            </div>

            <button type="submit" class="btn btn-primary">Create Environment</button>
        </form>
    </div>
</div>
@endsection

resources/views/environment/edit.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    Edit Environment: {{ $environment->name }}
@endsection
@section('breadcrumb', 'environment')
<div class="card uper">
    <div class="card-header">
        Edit Environment: <strong>{{ $environment->name }}</strong>
    </div>
    <div class="card-body">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div><br/>
        @endif
        <form method="post" action="{{ route('environments.update', $environment->id) }}">
            <div class="form-group">
                @csrf
                @method('PATCH')
                <label for="name">Environment Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $environment->name }}"/>
            </div>
            <div class="form-group">
                <label for="price">Environment Description:</label>
                <input type="text" class="form-control" name="description" value="{{ $environment->description }}"/>
            </div>

            <button type="submit" class="btn btn-primary">Update Environment</button>
        </form>
    </div>
</div>
@endsection

resources/views/environment/index.blade.php
@extends('layouts.master')

@section('content')

@section('pagename')
    List all environments
@endsection
@section('breadcrumb', 'Products')


<div class="uper pb-3">
    @if(session()->get('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div><br/>
    @endif

    <a href="{{ route('environments.create') }}" class="btn btn-primary" style="margin-bottom:10px">Create
        Environment </a>
    <section class="content">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List all environments</h3>
                    </div>
                    <div class="card-body">

                        <table id="example2" class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <td>ID</td>
                                <td>Name</td>
                                <td>Description</td>
                                <td colspan="2">Action</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($environments as $environment)
                                <tr>
                                    <td>{{$environment->id}}</td>
                                    <td>
                                        <a href="{{ route('environments.edit', $environment->id)}}">{{$environment->name}}</a>
                                    </td>
                                    <td>{{$environment->description}}</td>
                                    <td><a href="{{ route('environments.edit', $environment->id)}}"
                                           class="btn btn-primary">Edit</a></td>
                                    <td>
                                        <form action="{{ route('environments.destroy', $environment->id)}}"
                                              method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {!! $environments->links() !!}

    <div>
@endsection